window.TOOLBOX_ITEMS = [
    {
        "title":  "BPV HANDLEIDING Praktijkopleider WebAPP Praktijkbeoordelen",
        "fileName":  "BPV HANDLEIDING Praktijkopleider WebAPP Praktijkbeoordelen.pdf",
        "path":  "BPV EXAMENWERK/BPV HANDLEIDING Praktijkopleider WebAPP Praktijkbeoordelen.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  876,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Urenregistratie Praktijkbeoordelen Ontwikkelingsgericht",
        "fileName":  "BPV HANDLEIDING Urenregistratie Praktijkbeoordelen Ontwikkelingsgericht.pdf",
        "path":  "BPV EXAMENWERK/BPV HANDLEIDING Urenregistratie Praktijkbeoordelen Ontwikkelingsgericht.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  564,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING WebAPP Praktijkbeoordelen",
        "fileName":  "BPV HANDLEIDING WebAPP Praktijkbeoordelen.pdf",
        "path":  "BPV EXAMENWERK/BPV HANDLEIDING WebAPP Praktijkbeoordelen.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  969,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV INLOGGEGEVENS Examenwerk, Praktijkbeoordelen",
        "fileName":  "BPV INLOGGEGEVENS Examenwerk, Praktijkbeoordelen.pdf",
        "path":  "BPV EXAMENWERK/BPV INLOGGEGEVENS Examenwerk, Praktijkbeoordelen.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  235,
        "updated":  "10-07-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV STAPPENPLAN Beoordelaar Kwalificerend Praktijkbeoordelen",
        "fileName":  "BPV STAPPENPLAN Beoordelaar Kwalificerend Praktijkbeoordelen.pdf",
        "path":  "BPV EXAMENWERK/BPV STAPPENPLAN Beoordelaar Kwalificerend Praktijkbeoordelen.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  304,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV STAPPENPLAN Praktijkopleider Ontwikkelingsgericht Praktijkbeoordelen",
        "fileName":  "BPV STAPPENPLAN Praktijkopleider Ontwikkelingsgericht Praktijkbeoordelen.pdf",
        "path":  "BPV EXAMENWERK/BPV STAPPENPLAN Praktijkopleider Ontwikkelingsgericht Praktijkbeoordelen.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  320,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV STAPPENPLAN Student Ontwikkelingsgericht Praktijkbeoordelen",
        "fileName":  "BPV STAPPENPLAN Student Ontwikkelingsgericht Praktijkbeoordelen.pdf",
        "path":  "BPV EXAMENWERK/BPV STAPPENPLAN Student Ontwikkelingsgericht Praktijkbeoordelen.pdf",
        "category":  "BPV EXAMENWERK",
        "group":  "BPV EXAMENWERK",
        "extension":  "PDF",
        "sizeKb":  185,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV TEKST Agenda Kennismakingsgesprek",
        "fileName":  "BPV TEKST Agenda Kennismakingsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Agenda Kennismakingsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  32,
        "updated":  "17-06-2026",
        "copyText":  "TITEL: BPV Bedrijfsbezoek [Naam bedrijf] \u0027Kennismakingsgesprek\u0027 Albeda Horecacollege Rotterdam\r\n\r\nBeste [Naam praktijkopleider],\r\n\r\nNeem, ter voorbereiding op het geplande gesprek, even de tijd (ongeveer 15 minuten) om onderstaand formulier in te vullen door op de URL te klikken of de QR te scannen? Het zou geweldig zijn als je je antwoorden kunt inzenden vóór HIER DE GEWENSTE DATUM. Alvast bedankt voor de moeite!\r\n\r\nFormulier Kennismakingsgesprek Praktijkopleider\r\n\r\nURL:\r\n\r\nHier de QR\r\n\r\nBeste [Naam student],\r\n\r\nNeem, ter voorbereiding op het geplande gesprek, even de tijd (ongeveer 20 minuten) om onderstaand formulier in te vullen door op de URL te klikken of de QR te scannen? Het zou geweldig zijn als ook jij je antwoorden kunt inzenden vóór HIER DE GEWENSTE DATUM. Alvast bedankt voor de moeite!\r\n\r\nFormulier Kennismakingsgesprek Student\r\n\r\nURL:\r\n\r\nHier de QR\r\n\r\nAlvast bedankt voor je moeite!\r\n\r\nMet vriendelijke groet,\r\n\r\nJe naam en achternaam\r\nFunctie:\r\n\r\nE. email\r\nM. +31 mobiel\r\n\r\nAlbeda Horecacollege Rotterdam\r\nRosestraat 1101 | 3071 AL Rotterdam"
    },
    {
        "title":  "BPV TEKST Agenda Voortgangsgesprek",
        "fileName":  "BPV TEKST Agenda Voortgangsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Agenda Voortgangsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "TITEL: BPV Bedrijfsbezoek [naam rest.] \u0027Voortgangsgesprek\u0027 Albeda Horecacollege Rotterdam\r\n\r\nBeste [Naam praktijkopleider], Beste [Naam student],\r\n\r\nHierbij de afspraak m.b.t. het voortgangsgesprek die we tijdens het kennismakingsgesprek zijn overeengekomen. Eén week voordat het gesprek plaatsvindt ontvang je een herinnering. Bij deze herinnering zit voor beide een link die verwijst naar een Forms vragenlijst, dit ter voorbereiding op het gesprek. Het verzoek is deze uiterlijk twee dagen vóór het gesprek te hebben ingevuld en verzonden.\r\n\r\nAlvast bedankt voor de moeite.\r\n\r\nMet vriendelijke groet,\r\n\r\nJe naam en achternaam\r\nFunctie:\r\n\r\nE. email\r\nM. +31 mobiel\r\n\r\nAlbeda Horecacollege Rotterdam\r\nRosestraat 1101 | 3071 AL Rotterdam"
    },
    {
        "title":  "BPV TEKST Mail Eindbeoordeling PO",
        "fileName":  "BPV TEKST Mail Eindbeoordeling PO.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Mail Eindbeoordeling PO.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "01-07-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | Info Eindbeoordeling Student (QR)\r\n\r\nBeste [Naam praktijkopleider],\r\n\r\nOp 31 juli sluiten we qua BPV het schooljaar af en wordt de POK beëindigd. Dit betekent dat alle uren geregistreerd en geaccordeerd moeten zijn in Examenwerk evenals de nodige meetmomenten die moeten zijn vastgelegd. Neem, m.b.t. het afronden van de BPV ook even de tijd (ongeveer 25 minuten) om [naam student] te beoordelen middels onderstaand formulier. Dit doe je door op de URL te klikken of de QR te scannen en het formulier in te vullen? Het zou geweldig zijn als je je antwoorden kunt inzenden vóór HIER DE GEWENSTE DATUM. Alvast bedankt voor de moeite en de prettige samenwerking!\r\n\r\nFormulier Eindbeoordeling Praktijkopleider\r\n\r\nURL:\r\n\r\nHier de QR\r\n\r\nAlvast bedankt voor de moeite."
    },
    {
        "title":  "BPV TEKST Mail Eindbeoordeling ST",
        "fileName":  "BPV TEKST Mail Eindbeoordeling ST.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Mail Eindbeoordeling ST.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | Info Eindbeoordeling Leerbedrijf (QR)\r\n\r\nBeste [Naam student],\r\n\r\nOp 31 juli sluiten we qua BPV het schooljaar af en wordt de POK beëindigd. Dit betekent dat alle uren geregistreerd en geaccordeerd moeten zijn in Examenwerk evenals de nodige meetmomenten die moeten zijn vastgelegd. Neem, m.b.t. het afronden van de BPV ook even de tijd (ongeveer 25 minuten) om je leerbedrijf te beoordelen middels onderstaand formulier. Dit doe je door op de URL te klikken of de QR te scannen en het formulier in te vullen? Het zou geweldig zijn als je je antwoorden kunt inzenden vóór HIER DE GEWENSTE DATUM. Alvast bedankt voor de moeite en de prettige samenwerking!\r\n\r\nFormulier Eindbeoordeling Student\r\n\r\nURL:\r\n\r\nHier de QR\r\n\r\nAlvast bedankt voor de moeite."
    },
    {
        "title":  "BPV TEKST Mail Verslag Eindbeoordeling",
        "fileName":  "BPV TEKST Mail Verslag Eindbeoordeling.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Mail Verslag Eindbeoordeling.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | Verslag Eindbeoordeling [datum]\r\n\r\nBIJLAGEN: Document QR en Linkjes + Forms Beoordeling + PDF Verslag Eindbeoordeling\r\n\r\nBeste [Naam Praktijkopleider],\r\n\r\nDank voor je eindbeoordeling.\r\nZoals afgesproken in de bijlage een samenvatting van deze beoordeling m.b.t. [naam student].\r\nTevens wil ik je bedanken voor de prettige samenwerking en gesprekken.\r\n\r\nSucces en graag tot de volgende keer!"
    },
    {
        "title":  "BPV TEKST Mail Verslag Kennismakingsgesprek",
        "fileName":  "BPV TEKST Mail Verslag Kennismakingsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Mail Verslag Kennismakingsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | Verslag Kennismakingsgesprek [datum]\r\n\r\nBIJLAGEN: Document QR en Linkjes + E-learning (indien van toepassing) + PDF Verslag Kennismakingsgesprek\r\n\r\nBeste [Naam Praktijkopleider],\r\n\r\nNogmaals dank voor het gesprek.\r\nZoals afgesproken in de bijlage een samenvatting van het gesprek m.b.t. [Naam Student]. Tevens toegevoegd het document e-learning \u0027Praktijkbeoordelaar\u0027 (indien van toepassing, anders weglaten) en verschillende QR codes m.b.t. allerlei info en hulpmiddelen.\r\n\r\nSucces en tot de volgende keer!"
    },
    {
        "title":  "BPV TEKST Mail Verslag Voortgangsgesprek",
        "fileName":  "BPV TEKST Mail Verslag Voortgangsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Mail Verslag Voortgangsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | Verslag Voortgangsgesprek [datum]\r\n\r\nBIJLAGEN: Document QR en Linkjes + E-learning (indien van toepassing) + Forms Beoordeling + PDF Verslag Voortgangsgesprek\r\n\r\nBeste [Naam Praktijkopleider],\r\n\r\nNogmaals dank voor het gesprek.\r\nZoals afgesproken in de bijlage een samenvatting van het gesprek m.b.t. [Naam Student]. Nogmaals toegevoegd het document e-learning \u0027Praktijkbeoordelaar\u0027 (indien van toepassing, anders weglaten) en verschillende QR codes welke eerder met je gedeeld zijn, wellicht zijn ze aan je aandacht ontsnapt.\r\n\r\nSucces en tot de volgende keer!"
    },
    {
        "title":  "BPV TEKST Reminder Agenda Voortgangsgesprek",
        "fileName":  "BPV TEKST Reminder Agenda Voortgangsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Reminder Agenda Voortgangsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  30,
        "updated":  "16-06-2026",
        "copyText":  "Beste [Naam praktijkopleider], Beste [Naam student],\r\nGraag herinner ik je eraan dat wij volgende week [datum] om [tijd] uur een afspraak hebben staan m.b.t. een voortgangsgesprek. Neem ter voorbereiding op het geplande gesprek, even de tijd om de FORMS in te vullen door op de URL te klikken, ongeveer 20 minuten. Het zou geweldig zijn als je je antwoorden kunt inzenden vóór [datum]. Alvast bedankt voor de moeite! Met vriendelijke groet, Cees van den Heuvel | BPV Coördinator AHCR. URL PRAKTIJKOPLEIDER: Hier de url | URL LEERLING/STUDENT: hier de url"
    },
    {
        "title":  "BPV TEKST Reminder Mail Eindbeoordeling PO",
        "fileName":  "BPV TEKST Reminder Mail Eindbeoordeling PO.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Reminder Mail Eindbeoordeling PO.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | REMINDER Info Eindbeoordeling Student (QR)\r\n\r\nBeste [Naam praktijkopleider],\r\n\r\nOp [DATUM] heb je een mail ontvangen met een verzoek een eindbeoordeling in te vullen m.b.t. het afsluiten van de BPV. Bij dit verzoek heb je een QR en een linkje ontvangen die beide verwijzen naar de Forms. Wellicht is het aan je aandacht ontsnapt.\r\n\r\nHieronder nogmaals de QR en de link.\r\n\r\nFormulier Eindbeoordeling Student\r\n\r\nURL:\r\n\r\nHier de QR\r\n\r\nAlvast bedankt voor de moeite."
    },
    {
        "title":  "BPV TEKST Reminder Mail Eindbeoordeling ST",
        "fileName":  "BPV TEKST Reminder Mail Eindbeoordeling ST.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Reminder Mail Eindbeoordeling ST.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | REMINDER Info Eindbeoordeling Leerbedrijf (QR)\r\n\r\nBeste [Naam student],\r\n\r\nOp [DATUM] heb je een mail ontvangen met een verzoek een eindbeoordeling in te vullen m.b.t. het afsluiten van de BPV. Bij dit verzoek heb je een QR en een linkje ontvangen die beide verwijzen naar de Forms. Wellicht is het aan je aandacht ontsnapt.\r\n\r\nHieronder nogmaals de QR en de link.\r\n\r\nFormulier Eindbeoordeling Student\r\n\r\nURL:\r\n\r\nHier de QR\r\n\r\nAlvast bedankt voor de moeite."
    },
    {
        "title":  "BPV TEKST Reminder Mail Kennismakingsgesprek",
        "fileName":  "BPV TEKST Reminder Mail Kennismakingsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV KOPIEERTEKSTEN/BPV TEKST Reminder Mail Kennismakingsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV KOPIEERTEKSTEN",
        "extension":  "DOCX",
        "sizeKb":  31,
        "updated":  "16-06-2026",
        "copyText":  "ONDERWERP: Albeda Horecacollege Rotterdam | REMINDER Info Kennismakingsgesprek (QR)\r\n\r\nBeste [Naam praktijkopleider],\r\n\r\nOp [DATUM] hebben wij om [TIJDSTIP] een afspraak staan voor een bezoek/kennismakingsgesprek. Bij de bevestiging van deze afspraken heb je een QR en een linkje ontvangen die beide verwijzen naar een Forms. Het verzoek is om deze ter voorbereiding op het gesprek, in te vullen. Wellicht is het aan je aandacht ontsnapt.\r\n\r\nHieronder nogmaals de QR en de link.\r\n\r\nHier de QR\r\n\r\nURL:\r\n\r\nAlvast bedankt voor je moeite!"
    },
    {
        "title":  "BPV FORMULIER Check \u0026 Actie",
        "fileName":  "BPV FORMULIER Check \u0026 Actie.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV PDCA FORMULIEREN/BPV FORMULIER Check \u0026 Actie.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV PDCA FORMULIEREN",
        "extension":  "DOCX",
        "sizeKb":  47,
        "updated":  "14-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV FORMULIER Eindbeoordeling",
        "fileName":  "BPV FORMULIER Eindbeoordeling.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV PDCA FORMULIEREN/BPV FORMULIER Eindbeoordeling.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV PDCA FORMULIEREN",
        "extension":  "DOCX",
        "sizeKb":  43,
        "updated":  "14-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV FORMULIER Kennismakingsgesprek",
        "fileName":  "BPV FORMULIER Kennismakingsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV PDCA FORMULIEREN/BPV FORMULIER Kennismakingsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV PDCA FORMULIEREN",
        "extension":  "DOCX",
        "sizeKb":  48,
        "updated":  "14-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV FORMULIER Planning",
        "fileName":  "BPV FORMULIER Planning.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV PDCA FORMULIEREN/BPV FORMULIER Planning.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV PDCA FORMULIEREN",
        "extension":  "DOCX",
        "sizeKb":  41,
        "updated":  "11-10-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV FORMULIER Urenverantwoording",
        "fileName":  "BPV FORMULIER Urenverantwoording.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV PDCA FORMULIEREN/BPV FORMULIER Urenverantwoording.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV PDCA FORMULIEREN",
        "extension":  "DOCX",
        "sizeKb":  44,
        "updated":  "24-10-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV FORMULIER Voortgangsgesprek",
        "fileName":  "BPV FORMULIER Voortgangsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV PDCA FORMULIEREN/BPV FORMULIER Voortgangsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV PDCA FORMULIEREN",
        "extension":  "DOCX",
        "sizeKb":  43,
        "updated":  "04-11-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV TEMPLATE Verslag Eindbeoordeling",
        "fileName":  "BPV TEMPLATE Verslag Eindbeoordeling.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV TEMPLATES/BPV TEMPLATE Verslag Eindbeoordeling.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV TEMPLATES",
        "extension":  "DOCX",
        "sizeKb":  41,
        "updated":  "13-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV TEMPLATE Verslag Kennismakingsgesprek",
        "fileName":  "BPV TEMPLATE Verslag Kennismakingsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV TEMPLATES/BPV TEMPLATE Verslag Kennismakingsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV TEMPLATES",
        "extension":  "DOCX",
        "sizeKb":  46,
        "updated":  "14-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV TEMPLATE Verslag Voortgangsgesprek",
        "fileName":  "BPV TEMPLATE Verslag Voortgangsgesprek.docx",
        "path":  "BPV FORMULIEREN \u0026 TEMPLATES/BPV TEMPLATES/BPV TEMPLATE Verslag Voortgangsgesprek.docx",
        "category":  "BPV FORMULIEREN \u0026 TEMPLATES",
        "group":  "BPV TEMPLATES",
        "extension":  "DOCX",
        "sizeKb":  44,
        "updated":  "13-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Bedrijfsbezoeken AHCR",
        "fileName":  "BPV HANDLEIDING Bedrijfsbezoeken AHCR.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING Bedrijfsbezoeken AHCR.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  366,
        "updated":  "18-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Beeindigen BPV Student 1",
        "fileName":  "BPV HANDLEIDING Beeindigen BPV Student 1.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING Beeindigen BPV Student 1.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  1615,
        "updated":  "15-05-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Beeindigen BPV Student 2",
        "fileName":  "BPV HANDLEIDING Beeindigen BPV Student 2.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING Beeindigen BPV Student 2.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  10956,
        "updated":  "18-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING My Signature 191225",
        "fileName":  "BPV HANDLEIDING My Signature 191225.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING My Signature 191225.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  10904,
        "updated":  "19-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING ROUTEKAART BBL coach",
        "fileName":  "BPV HANDLEIDING ROUTEKAART BBL coach.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING ROUTEKAART BBL coach.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  400,
        "updated":  "29-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING ROUTEKAART BOL coach",
        "fileName":  "BPV HANDLEIDING ROUTEKAART BOL coach.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING ROUTEKAART BOL coach.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  395,
        "updated":  "29-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Student Matcht Zelfstandig 141225",
        "fileName":  "BPV HANDLEIDING Student Matcht Zelfstandig 141225.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV HANDLEIDING Student Matcht Zelfstandig 141225.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  8288,
        "updated":  "14-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV INFOGRAPHIC Bedrijfsbezoeken",
        "fileName":  "BPV INFOGRAPHIC Bedrijfsbezoeken.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV INFOGRAPHIC Bedrijfsbezoeken.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  522,
        "updated":  "11-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV INFOGRAPHIC Beeindigen BPV Student 181225",
        "fileName":  "BPV INFOGRAPHIC Beeindigen BPV Student 181225.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV INFOGRAPHIC Beeindigen BPV Student 181225.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  579,
        "updated":  "29-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV INFOGRAPHIC Student Matcht Zelfstandig 141225",
        "fileName":  "BPV INFOGRAPHIC Student Matcht Zelfstandig 141225.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV INFOGRAPHIC Student Matcht Zelfstandig 141225.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  499,
        "updated":  "29-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV VOORBEELD POK+BPV-blad+NL+Digitaal Getekend",
        "fileName":  "BPV VOORBEELD POK+BPV-blad+NL+Digitaal Getekend.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV VOORBEELD POK+BPV-blad+NL+Digitaal Getekend.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  190,
        "updated":  "05-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV VOORBEELD POK+BPV-blad+NL+Digitaal Niet Getekend",
        "fileName":  "BPV VOORBEELD POK+BPV-blad+NL+Digitaal Niet Getekend.pdf",
        "path":  "BPV HANDLEIDINGEN/BPV VOORBEELD POK+BPV-blad+NL+Digitaal Niet Getekend.pdf",
        "category":  "BPV HANDLEIDINGEN",
        "group":  "BPV HANDLEIDINGEN",
        "extension":  "PDF",
        "sizeKb":  174,
        "updated":  "05-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV BRIEF Stagevergoeding 2024",
        "fileName":  "BPV BRIEF Stagevergoeding 2024.pdf",
        "path":  "BPV INFO PRAKTIJKOPLEIDERS/BPV BRIEF Stagevergoeding 2024.pdf",
        "category":  "BPV INFO PRAKTIJKOPLEIDERS",
        "group":  "BPV INFO PRAKTIJKOPLEIDERS",
        "extension":  "PDF",
        "sizeKb":  108,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV E-LEARNING Praktijkbeoordelaar",
        "fileName":  "BPV E-LEARNING Praktijkbeoordelaar.pdf",
        "path":  "BPV INFO PRAKTIJKOPLEIDERS/BPV E-LEARNING Praktijkbeoordelaar.pdf",
        "category":  "BPV INFO PRAKTIJKOPLEIDERS",
        "group":  "BPV INFO PRAKTIJKOPLEIDERS",
        "extension":  "PDF",
        "sizeKb":  119,
        "updated":  "04-08-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Check je Pok",
        "fileName":  "BPV HANDLEIDING Check je Pok.pdf",
        "path":  "BPV INFO PRAKTIJKOPLEIDERS/BPV HANDLEIDING Check je Pok.pdf",
        "category":  "BPV INFO PRAKTIJKOPLEIDERS",
        "group":  "BPV INFO PRAKTIJKOPLEIDERS",
        "extension":  "PDF",
        "sizeKb":  393,
        "updated":  "09-07-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Praktijkopleiders AHCR",
        "fileName":  "BPV HANDLEIDING Praktijkopleiders AHCR.pdf",
        "path":  "BPV INFO PRAKTIJKOPLEIDERS/BPV HANDLEIDING Praktijkopleiders AHCR.pdf",
        "category":  "BPV INFO PRAKTIJKOPLEIDERS",
        "group":  "BPV INFO PRAKTIJKOPLEIDERS",
        "extension":  "PDF",
        "sizeKb":  789,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV INSTRUCTIES MijnSBB",
        "fileName":  "BPV INSTRUCTIES MijnSBB.pdf",
        "path":  "BPV INFO PRAKTIJKOPLEIDERS/BPV INSTRUCTIES MijnSBB.pdf",
        "category":  "BPV INFO PRAKTIJKOPLEIDERS",
        "group":  "BPV INFO PRAKTIJKOPLEIDERS",
        "extension":  "PDF",
        "sizeKb":  130,
        "updated":  "08-08-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV QR ONEDRIVE en CHATGPT Praktijkopleiders versie 3",
        "fileName":  "BPV QR ONEDRIVE en CHATGPT Praktijkopleiders versie 3.pdf",
        "path":  "BPV INFO PRAKTIJKOPLEIDERS/BPV QR ONEDRIVE en CHATGPT Praktijkopleiders versie 3.pdf",
        "category":  "BPV INFO PRAKTIJKOPLEIDERS",
        "group":  "BPV INFO PRAKTIJKOPLEIDERS",
        "extension":  "PDF",
        "sizeKb":  241,
        "updated":  "05-01-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV FORMULIER Leerbedrijf \u0026 Matching",
        "fileName":  "BPV FORMULIER Leerbedrijf \u0026 Matching.docx",
        "path":  "BPV INFO STUDENTEN/BPV FORMULIER Leerbedrijf \u0026 Matching.docx",
        "category":  "BPV INFO STUDENTEN",
        "group":  "BPV INFO STUDENTEN",
        "extension":  "DOCX",
        "sizeKb":  44,
        "updated":  "05-10-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Check je Pok",
        "fileName":  "BPV HANDLEIDING Check je Pok.pdf",
        "path":  "BPV INFO STUDENTEN/BPV HANDLEIDING Check je Pok.pdf",
        "category":  "BPV INFO STUDENTEN",
        "group":  "BPV INFO STUDENTEN",
        "extension":  "PDF",
        "sizeKb":  393,
        "updated":  "09-07-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING Student Matcht Zelfstandig 141225",
        "fileName":  "BPV HANDLEIDING Student Matcht Zelfstandig 141225.pdf",
        "path":  "BPV INFO STUDENTEN/BPV HANDLEIDING Student Matcht Zelfstandig 141225.pdf",
        "category":  "BPV INFO STUDENTEN",
        "group":  "BPV INFO STUDENTEN",
        "extension":  "PDF",
        "sizeKb":  8288,
        "updated":  "14-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV ROUTEKAART BBL volledig",
        "fileName":  "BPV ROUTEKAART BBL volledig.pdf",
        "path":  "BPV INFO STUDENTEN/BPV ROUTEKAART BBL volledig.pdf",
        "category":  "BPV INFO STUDENTEN",
        "group":  "BPV INFO STUDENTEN",
        "extension":  "PDF",
        "sizeKb":  538,
        "updated":  "03-07-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV ROUTEKAART BOL volledig",
        "fileName":  "BPV ROUTEKAART BOL volledig.pdf",
        "path":  "BPV INFO STUDENTEN/BPV ROUTEKAART BOL volledig.pdf",
        "category":  "BPV INFO STUDENTEN",
        "group":  "BPV INFO STUDENTEN",
        "extension":  "PDF",
        "sizeKb":  536,
        "updated":  "03-07-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Leidinggevende Hospitality",
        "fileName":  "Nieuw Beroepsbeschrijving Leidinggevende Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Beroepsbeschrijving Leidinggevende Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  20,
        "updated":  "13-02-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Medewerker Hospitality",
        "fileName":  "Nieuw Beroepsbeschrijving Medewerker Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Beroepsbeschrijving Medewerker Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Zelfstandig Medewerker Hospitality",
        "fileName":  "Nieuw Beroepsbeschrijving Zelfstandig Medewerker Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Beroepsbeschrijving Zelfstandig Medewerker Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Leidinggevende Hospitality",
        "fileName":  "Nieuw Kwalificatiedossier Leidinggevende Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Kwalificatiedossier Leidinggevende Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  278,
        "updated":  "13-02-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Medewerker Hospitality",
        "fileName":  "Nieuw Kwalificatiedossier Medewerker Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Kwalificatiedossier Medewerker Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  243,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Zelfstandig Medewerker Hospitality",
        "fileName":  "Nieuw Kwalificatiedossier Zelfstandig Medewerker Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Kwalificatiedossier Zelfstandig Medewerker Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  260,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Verantwoordingsinformatie Hospitality, Tourism \u0026 Leisure",
        "fileName":  "Nieuw Verantwoordingsinformatie Hospitality, Tourism \u0026 Leisure.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Nieuw Verantwoordingsinformatie Hospitality, Tourism \u0026 Leisure.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  147,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Gespecialiseerd Kok",
        "fileName":  "Nieuw Beroepsbeschrijving Gespecialiseerd Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Beroepsbeschrijving Gespecialiseerd Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  20,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Kok",
        "fileName":  "Nieuw Beroepsbeschrijving Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Beroepsbeschrijving Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Leidinggevende Keuken",
        "fileName":  "Nieuw Beroepsbeschrijving Leidinggevende Keuken.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Beroepsbeschrijving Leidinggevende Keuken.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  20,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Zelfstandig Werkend Kok",
        "fileName":  "Nieuw Beroepsbeschrijving Zelfstandig Werkend Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Beroepsbeschrijving Zelfstandig Werkend Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  20,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Gespecialiseerd Kok",
        "fileName":  "Nieuw Kwalificatiedossier Gespecialiseerd Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Kwalificatiedossier Gespecialiseerd Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  264,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Kok",
        "fileName":  "Nieuw Kwalificatiedossier Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Kwalificatiedossier Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  235,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Leidinggevende Keuken",
        "fileName":  "Nieuw Kwalificatiedossier Leidinggevende Keuken.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Kwalificatiedossier Leidinggevende Keuken.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  265,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Zelfstandig Werkend Kok",
        "fileName":  "Nieuw Kwalificatiedossier Zelfstandig Werkend Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Kwalificatiedossier Zelfstandig Werkend Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  253,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Verantwoordingsinformatie Keuken \u0026 Foodservice",
        "fileName":  "Nieuw Verantwoordingsinformatie Keuken \u0026 Foodservice.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Nieuw Verantwoordingsinformatie Keuken \u0026 Foodservice.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  122,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Beroepsbeschrijving Ondernemer Hospitality",
        "fileName":  "Nieuw Beroepsbeschrijving Ondernemer Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Nieuw Beroepsbeschrijving Ondernemer Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Kwalificatiedossier Ondernemer Hospitality",
        "fileName":  "Nieuw Kwalificatiedossier Ondernemer Hospitality.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Nieuw Kwalificatiedossier Ondernemer Hospitality.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  283,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Nieuw Verantwoordingsinformatie Hospitality, Tourism \u0026 Leisure",
        "fileName":  "Nieuw Verantwoordingsinformatie Hospitality, Tourism \u0026 Leisure.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/NIEUW KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Nieuw Verantwoordingsinformatie Hospitality, Tourism \u0026 Leisure.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "NIEUW KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  147,
        "updated":  "15-01-2026",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Gastheer-vrouw",
        "fileName":  "Oud Beroepsbeschrijving Gastheer-vrouw.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Beroepsbeschrijving Gastheer-vrouw.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Leidinggevende Bediening",
        "fileName":  "Oud Beroepsbeschrijving Leidinggevende Bediening.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Beroepsbeschrijving Leidinggevende Bediening.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  20,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Zelfstandig Werkend Gastheer-Vrouw",
        "fileName":  "Oud Beroepsbeschrijving Zelfstandig Werkend Gastheer-Vrouw.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Beroepsbeschrijving Zelfstandig Werkend Gastheer-Vrouw.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  20,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Gastheer-Vrouw",
        "fileName":  "Oud Kwalificatiedossier Gastheer-Vrouw.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Kwalificatiedossier Gastheer-Vrouw.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  225,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Leidinggevende Bediening",
        "fileName":  "Oud Kwalificatiedossier Leidinggevende Bediening.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Kwalificatiedossier Leidinggevende Bediening.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  274,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Zelfstandig Werkend Gastheer-Vrouw",
        "fileName":  "Oud Kwalificatiedossier Zelfstandig Werkend Gastheer-Vrouw.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Kwalificatiedossier Zelfstandig Werkend Gastheer-Vrouw.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  251,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Verantwoordingsinformatie Bediening",
        "fileName":  "Oud Verantwoordingsinformatie Bediening.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027/Oud Verantwoordingsinformatie Bediening.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  105,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Gespecialiseerd Kok",
        "fileName":  "Oud Beroepsbeschrijving Gespecialiseerd Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Beroepsbeschrijving Gespecialiseerd Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Kok",
        "fileName":  "Oud Beroepsbeschrijving Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Beroepsbeschrijving Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  18,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Leidinggevende Keuken",
        "fileName":  "Oud Beroepsbeschrijving Leidinggevende Keuken.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Beroepsbeschrijving Leidinggevende Keuken.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Zelfstandig Werkend Kok",
        "fileName":  "Oud Beroepsbeschrijving Zelfstandig Werkend Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Beroepsbeschrijving Zelfstandig Werkend Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Gespecialiseerd Kok",
        "fileName":  "Oud Kwalificatiedossier Gespecialiseerd Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Kwalificatiedossier Gespecialiseerd Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  260,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Kok",
        "fileName":  "Oud Kwalificatiedossier Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Kwalificatiedossier Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  223,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Leidinggevende Keuken",
        "fileName":  "Oud Kwalificatiedossier Leidinggevende Keuken.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Kwalificatiedossier Leidinggevende Keuken.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  263,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Zelfstandig Werkend Kok",
        "fileName":  "Oud Kwalificatiedossier Zelfstandig Werkend Kok.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Kwalificatiedossier Zelfstandig Werkend Kok.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  246,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Verantwoordingsinformatie Keuken",
        "fileName":  "Oud Verantwoordingsinformatie Keuken.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027/Oud Verantwoordingsinformatie Keuken.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  97,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Manager Ondernemer Horeca",
        "fileName":  "Oud Beroepsbeschrijving Manager Ondernemer Horeca.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Oud Beroepsbeschrijving Manager Ondernemer Horeca.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Beroepsbeschrijving Meewerkend Horeca Ondernemer",
        "fileName":  "Oud Beroepsbeschrijving Meewerkend Horeca Ondernemer.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Oud Beroepsbeschrijving Meewerkend Horeca Ondernemer.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  19,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Manager Ondernemer Horeca",
        "fileName":  "Oud Kwalificatiedossier Manager Ondernemer Horeca.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Oud Kwalificatiedossier Manager Ondernemer Horeca.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  270,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Kwalificatiedossier Meewerkend Horeca Ondernemer",
        "fileName":  "Oud Kwalificatiedossier Meewerkend Horeca Ondernemer.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Oud Kwalificatiedossier Meewerkend Horeca Ondernemer.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  260,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "Oud Verantwoordingsinformatie Ondernemer",
        "fileName":  "Oud Verantwoordingsinformatie Ondernemer.pdf",
        "path":  "BPV KWALIFICATIEDOSSIERS/OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027/Oud Verantwoordingsinformatie Ondernemer.pdf",
        "category":  "BPV KWALIFICATIEDOSSIERS",
        "group":  "OUD KWALIFICATIEDOSSIER \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  97,
        "updated":  "18-07-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN GHV 25168",
        "fileName":  "BPV OPDRACHTEN GHV 25168.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/BPV OPDRACHTEN GHV 25168.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  160,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN LGB 25170",
        "fileName":  "BPV OPDRACHTEN LGB 25170.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/BPV OPDRACHTEN LGB 25170.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  178,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN ZWG 25171",
        "fileName":  "BPV OPDRACHTEN ZWG 25171.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/BPV OPDRACHTEN ZWG 25171.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  177,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN ZWG-LGB Tafelbereidingen \u0026 Technieken",
        "fileName":  "BPV OPDRACHTEN ZWG-LGB Tafelbereidingen \u0026 Technieken.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/BPV OPDRACHTEN ZWG-LGB Tafelbereidingen \u0026 Technieken.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  219,
        "updated":  "25-08-2025",
        "copyText":  ""
    },
    {
        "title":  "LMS BEROEPSTAKEN Bar",
        "fileName":  "LMS BEROEPSTAKEN Bar.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/LMS BEROEPSTAKEN Bar.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  169,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "LMS BEROEPSTAKEN Facilitair",
        "fileName":  "LMS BEROEPSTAKEN Facilitair.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/LMS BEROEPSTAKEN Facilitair.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  219,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "LMS BEROEPSTAKEN Financieel",
        "fileName":  "LMS BEROEPSTAKEN Financieel.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/LMS BEROEPSTAKEN Financieel.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  212,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "LMS BEROEPSTAKEN GHV",
        "fileName":  "LMS BEROEPSTAKEN GHV.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/LMS BEROEPSTAKEN GHV.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  248,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "LMS BEROEPSTAKEN Pas",
        "fileName":  "LMS BEROEPSTAKEN Pas.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/LMS BEROEPSTAKEN Pas.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  142,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "LMS BEROEPSTAKEN Runner",
        "fileName":  "LMS BEROEPSTAKEN Runner.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027BEDIENING\u0027/LMS BEROEPSTAKEN Runner.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027BEDIENING\u0027",
        "extension":  "PDF",
        "sizeKb":  235,
        "updated":  "07-10-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV HANDLEIDING My Signature 191225",
        "fileName":  "BPV HANDLEIDING My Signature 191225.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV HANDLEIDING My Signature 191225.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  10904,
        "updated":  "19-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHT My Signature ZWK, GSK, LGK",
        "fileName":  "BPV OPDRACHT My Signature ZWK, GSK, LGK.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV OPDRACHT My Signature ZWK, GSK, LGK.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  480,
        "updated":  "08-08-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN GSK 25179",
        "fileName":  "BPV OPDRACHTEN GSK 25179.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV OPDRACHTEN GSK 25179.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  172,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN KOK 25180",
        "fileName":  "BPV OPDRACHTEN KOK 25180.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV OPDRACHTEN KOK 25180.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  160,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN LGK 25181",
        "fileName":  "BPV OPDRACHTEN LGK 25181.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV OPDRACHTEN LGK 25181.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  173,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN ZWK 25182",
        "fileName":  "BPV OPDRACHTEN ZWK 25182.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV OPDRACHTEN ZWK 25182.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "PDF",
        "sizeKb":  171,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV TAKENBOEK KOK, ZWK, GSK, LGK",
        "fileName":  "BPV TAKENBOEK KOK, ZWK, GSK, LGK.docx",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV TAKENBOEK KOK, ZWK, GSK, LGK.docx",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "DOCX",
        "sizeKb":  452,
        "updated":  "25-08-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV VOORBEELD_UITWERKING_VIJFTIEN-GANGEN-MENU",
        "fileName":  "BPV VOORBEELD_UITWERKING_VIJFTIEN-GANGEN-MENU.docx",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027KEUKEN\u0027/BPV VOORBEELD_UITWERKING_VIJFTIEN-GANGEN-MENU.docx",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027KEUKEN\u0027",
        "extension":  "DOCX",
        "sizeKb":  122,
        "updated":  "15-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN MHO 25185",
        "fileName":  "BPV OPDRACHTEN MHO 25185.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027MANAGEMENT\u0027/BPV OPDRACHTEN MHO 25185.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  172,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV OPDRACHTEN MOH 25184",
        "fileName":  "BPV OPDRACHTEN MOH 25184.pdf",
        "path":  "BPV OPDRACHTEN/BPV OPDRACHTEN \u0027MANAGEMENT\u0027/BPV OPDRACHTEN MOH 25184.pdf",
        "category":  "BPV OPDRACHTEN",
        "group":  "BPV OPDRACHTEN \u0027MANAGEMENT\u0027",
        "extension":  "PDF",
        "sizeKb":  178,
        "updated":  "16-09-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV PRESENTATIE Bedrijfsbezoeken",
        "fileName":  "BPV PRESENTATIE Bedrijfsbezoeken.pdf",
        "path":  "BPV PRESENTATIES/BPV PRESENTATIE Bedrijfsbezoeken.pdf",
        "category":  "BPV PRESENTATIES",
        "group":  "BPV PRESENTATIES",
        "extension":  "PDF",
        "sizeKb":  5890,
        "updated":  "11-12-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV PRESENTATIE Info Website Albeda",
        "fileName":  "BPV PRESENTATIE Info Website Albeda.pdf",
        "path":  "BPV PRESENTATIES/BPV PRESENTATIE Info Website Albeda.pdf",
        "category":  "BPV PRESENTATIES",
        "group":  "BPV PRESENTATIES",
        "extension":  "PDF",
        "sizeKb":  15639,
        "updated":  "12-01-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV MS-FORMS Url\u0027s Gespreksformulieren",
        "fileName":  "BPV MS-FORMS Url\u0027s Gespreksformulieren.pdf",
        "path":  "BPV QR \u0026 LINKS/BPV MS-FORMS Url\u0027s Gespreksformulieren.pdf",
        "category":  "BPV QR \u0026 LINKS",
        "group":  "BPV QR \u0026 LINKS",
        "extension":  "PDF",
        "sizeKb":  138,
        "updated":  "23-11-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV QR ONEDRIVE en CHATGPT praktijkopleiders versie 3",
        "fileName":  "BPV QR ONEDRIVE en CHATGPT praktijkopleiders versie 3.pdf",
        "path":  "BPV QR \u0026 LINKS/BPV QR ONEDRIVE en CHATGPT praktijkopleiders versie 3.pdf",
        "category":  "BPV QR \u0026 LINKS",
        "group":  "BPV QR \u0026 LINKS",
        "extension":  "PDF",
        "sizeKb":  241,
        "updated":  "05-01-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV YOUTUBE Tutorials",
        "fileName":  "BPV YOUTUBE Tutorials.pdf",
        "path":  "BPV QR \u0026 LINKS/BPV YOUTUBE Tutorials.pdf",
        "category":  "BPV QR \u0026 LINKS",
        "group":  "BPV QR \u0026 LINKS",
        "extension":  "PDF",
        "sizeKb":  102,
        "updated":  "08-08-2025",
        "copyText":  ""
    },
    {
        "title":  "BPV SCHOOLPERIODE KALENDER BBL BLJ 1e, 2e en 3e jaars 2627",
        "fileName":  "BPV SCHOOLPERIODE KALENDER BBL BLJ 1e, 2e en 3e jaars 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV SCHOOLPERIODE KALENDER BBL BLJ 1e, 2e en 3e jaars 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  276,
        "updated":  "29-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV SCHOOLPERIODE KALENDER BBL RSS 1e, 2e en 3e jaars 2627",
        "fileName":  "BPV SCHOOLPERIODE KALENDER BBL RSS 1e, 2e en 3e jaars 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV SCHOOLPERIODE KALENDER BBL RSS 1e, 2e en 3e jaars 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  276,
        "updated":  "24-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV STAGEPERIODE KALENDER BOL 1e jaars 2627",
        "fileName":  "BPV STAGEPERIODE KALENDER BOL 1e jaars 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV STAGEPERIODE KALENDER BOL 1e jaars 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  276,
        "updated":  "24-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV STAGEPERIODE KALENDER BOL 2e jaars (1) 2627",
        "fileName":  "BPV STAGEPERIODE KALENDER BOL 2e jaars (1) 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV STAGEPERIODE KALENDER BOL 2e jaars (1) 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  279,
        "updated":  "24-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV STAGEPERIODE KALENDER BOL 2e jaars (2) 2627",
        "fileName":  "BPV STAGEPERIODE KALENDER BOL 2e jaars (2) 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV STAGEPERIODE KALENDER BOL 2e jaars (2) 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  279,
        "updated":  "24-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV STAGEPERIODE KALENDER BOL 3e jaars 2627",
        "fileName":  "BPV STAGEPERIODE KALENDER BOL 3e jaars 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV STAGEPERIODE KALENDER BOL 3e jaars 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  278,
        "updated":  "25-06-2026",
        "copyText":  ""
    },
    {
        "title":  "BPV STAGEPERIODE KALENDER BOL 4e jaars 2627",
        "fileName":  "BPV STAGEPERIODE KALENDER BOL 4e jaars 2627.pdf",
        "path":  "BPV STAGE-KALENDERS/BPV STAGEPERIODE KALENDER BOL 4e jaars 2627.pdf",
        "category":  "BPV STAGE-KALENDERS",
        "group":  "BPV STAGE-KALENDERS",
        "extension":  "PDF",
        "sizeKb":  278,
        "updated":  "24-06-2026",
        "copyText":  ""
    }
];